name: Markdown to HTML

on:
  push:
    branches:
      - main

jobs:
  Job:
    runs-on: windows-latest
    steps:
      - name: Convert Markdown to HTML
        uses: natescherer/markdown-to-html-with-github-style-action@v1.0.0
        with:
          path: README.md,Jetbrains%20CLion%20簡述/Jetbrains%20CLion%20使用.md
          outputpath: out

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Convert Markdown to HTML"
          git push
